import { WarehouseItem } from "@/contexts/warehouse-context";

export const warehouses: WarehouseItem[] = [
  {
    id: "WH001",
    name: "Main Distribution Center",
    location: "Atlanta, GA",
    code: "ATL-DC",
    status: "active",
    capacity: 50000,
    currentLoad: 32500,
    staff: 45,
  },
  {
    id: "WH002",
    name: "West Coast Hub",
    location: "Los Angeles, CA",
    code: "LAX-HUB",
    status: "active",
    capacity: 35000,
    currentLoad: 28900,
    staff: 32,
  },
  {
    id: "WH003",
    name: "Northeast Facility",
    location: "Newark, NJ",
    code: "EWR-FAC",
    status: "active",
    capacity: 42000,
    currentLoad: 18750,
    staff: 38,
  },
  {
    id: "WH004",
    name: "Chicago Processing",
    location: "Chicago, IL",
    code: "CHI-PROC",
    status: "maintenance",
    capacity: 28000,
    currentLoad: 0,
    staff: 15,
  },
  {
    id: "WH005",
    name: "Texas Regional",
    location: "Dallas, TX",
    code: "DFW-REG",
    status: "active",
    capacity: 38000,
    currentLoad: 22100,
    staff: 29,
  },
]
